version: "3.7"

services:
  demo:
    build: .
    container_name: demo
    ports:
      - 8080:2999
    entrypoint: ["npm", "demo/dist/index.js"]
    depends_on:
      - mongodb
      - keycloak
      - demo-connector

  school:
    build: .
    container_name: school
    ports:
      - 8081:2999
    entrypoint: ["npm", "school/dist/index.js"]
    depends_on:
      - mongodb
      - keycloak
      - school-connector

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - demo_mongo_data:/data/db

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    volumes:
      - ./config/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
    command: start
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  demo_mongo_data:
  postgres_data:
