version: "3.7"

services:
  website-demo:
    build: .
    container_name: website-demo
    ports:
      - 2901:2999
    working_dir: "/usr/app/demo"
    depends_on:
      - mongodb
      - keycloak
      - connector-demo

  connector-demo:
    container_name: connector-demo
    image: ghcr.io/nmshd/connector:3.10.1
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - transportLibrary__baseUrl
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
    volumes:
      - ./config/connector-demo-config.json:/config.json:ro
    depends_on:
      - mongodb

  website-school:
    build: .
    container_name: website-school
    ports:
      - 2902:2999
    working_dir: "/usr/app/school"
    depends_on:
      - mongodb
      - keycloak
      - connector-school

  connector-school:
    container_name: connector-school
    image: ghcr.io/nmshd/connector:3.10.1
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - transportLibrary__baseUrl
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
    volumes:
      - ./config/connector-school-config.json:/config.json:ro
    depends_on:
      - mongodb

  website-university:
    build: .
    container_name: website-university
    ports:
      - 2903:2999
    working_dir: "/usr/app/university"
    depends_on:
      - mongodb
      - keycloak
      - connector-university

  connector-university:
    container_name: connector-university
    image: ghcr.io/nmshd/connector:3.10.1
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - transportLibrary__baseUrl
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
    volumes:
      - ./config/connector-university-config.json:/config.json:ro
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - demo_mongo_data:/data/db

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    volumes:
      - ./config/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
    command: start-dev
    depends_on:
      - postgres

volumes:
  demo_mongo_data:
  postgres_data:
